- src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackParticipantsController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackParticipantResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/Track.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackParticipantId.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackParticipants.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackParticipantsRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackParticipantsService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackService.java
- src/main/java/wercsmik/spaghetticodingclub/global/auditing/BaseTimeEntity.java
- src/main/java/wercsmik/spaghetticodingclub/global/auditing/JpaAuditingConfiguration.java
- src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
- 트랙 생성, 조회, 참가자 추가 및 조회 기능을 구현하였습니다. 이는 사용자와 관리자 모두에게 트랙 관련 정보를 효율적으로 관리할 수 있는 기능을 제공합니다.
1. **트랙 생성 기능과 API**
- 관리자만 트랙을 생성할 수 있는 기능을 구현하였습니다. 트랙명은 고유해야 하며, 중복된 트랙명으로 생성 시도 시 오류를 반환합니다.
2. **트랙 조회 기능과 API**
- 모든 사용자가 등록된 트랙 목록을 조회할 수 있는 기능을 구현하였습니다. 이를 통해 사용자는 다양한 트랙 정보를 쉽게 접근할 수 있습니다.
3. **트랙 참가자 추가 기능**
- 사용자가 특정 트랙의 참가자로 추가될 수 있는 기능을 구현하였습니다. 참가자 추가 시 현재 시간이 참가 시점으로 기록됩니다.
4. **트랙 참가자 조회 기능과 API**
- 특정 트랙의 모든 참가자를 조회할 수 있는 기능을 구현하였습니다. 이를 통해 사용자는 트랙별 참가자 정보를 쉽게 확인할 수 있습니다.
- Postman을 통한 테스트를 통해 각 기능의 정상 작동을 확인하였고 테스트를 통해 기능의 안정성을 검증하였습니다.
- 트랙 관련 기능의 구현을 통해 사용자와 관리자는 트랙 정보를 효율적으로 관리할 수 있게 되었습니다.
> 트랙 관련 기능 구현: 생성, 조회, 참가자 추가 및 조회

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackParticipantsController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackParticipantUpdateResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackUpdateRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackParticipants.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackParticipantsService.java
관리자가 트랙 참여자의 트랙을 수정할 수 있도록 하는 기능입니다. 이 기능은 관리자 권한을 가진 사용자만이 접근할 수 있으며, 트랙 참여자의 기존 트랙 ID와 새로운 트랙 이름을 통해 트랙 정보를 업데이트합니다.
- `TrackParticipantsService` 클래스에 `updateParticipantTrack` 메소드를 추가하여, 트랙 수정 로직을 처리합니다.
- `TrackParticipantsController`에 `updateParticipantTrack` 엔드포인트를 추가하여, URL 경로를 통해 사용자 ID와 기존 트랙 ID를 받고, 요청 본문을 통해 새 트랙 이름을 받습니다.
- 새로운 DTO `TrackParticipantUpdateResponseDTO`를 정의하여, 수정된 사용자 ID와 트랙 이름을 응답으로 반환합니다.
- 이 기능은 `@PreAuthorize` 어노테이션을 사용하여 `ROLE_ADMIN` 권한을 가진 사용자만 접근할 수 있습니다.
- 요청이 처리되기 전에 사용자의 권한을 검증합니다.
- 모든 변경 사항은 Postman을 통해 검증되었습니다.
> feat: 트랙 참여자의 트랙 수정

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackNoticeController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackNoticeCreationRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackNoticeResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackNotice.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackNoticeRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackNoticeService.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
이 Pull Request는 트랙명 수정 기능을 구현합니다. 관리자만이 트랙의 이름을 수정할 수 있으며, 이를 통해 트랙 정보를 더욱 유동적으로 관리할 수 있습니다. 수정된 트랙 정보는 응답으로 반환되어 클라이언트가 변경 사항을 즉시 확인할 수 있습니다.
- `TrackService`에 `updateTrackName` 메소드를 추가하여 트랙명을 업데이트하는 로직을 구현했습니다.
- `TrackController`에서 해당 서비스 메소드를 호출하는 새로운 PUT 엔드포인트 `/tracks/{trackId}`를 추가했습니다.
- 새로운 응답 DTO `TrackUpdateResponseDTO`를 추가하여 수정된 트랙명과 트랙 ID를 클라이언트에 반환합니다.
- `@PreAuthorize` 어노테이션을 사용하여 이 기능에 대한 접근을 관리자로 제한했습니다.
- 트랙 정보의 유지 관리가 용이해집니다.
- 관리자는 트랙 정보를 실시간으로 업데이트할 수 있으며, 이 변경 사항은 즉시 시스템에 반영됩니다.
- 시스템의 유연성이 향상되며 사용자 경험이 개선됩니다.
- Postman을 통해 `updateTrackName` 메소드의 기능을 검증했습니다.
> feat: 트랙 공지 생성

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackNoticeController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackNotice.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackParticipants.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackNoticeRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackParticipantsRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackNoticeService.java
- src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
이 Pull Request는 트랙 공지 API의 기능을 강화하며, 관리자와 일반 사용자의 접근성을 개선하는 새로운 로직을 도입합니다. 특히, 관리자는 특정 트랙 ID를 제공할 경우 해당 트랙의 공지만 조회할 수 있으며, 모든 공지를 조회하는 기능도 포함됩니다.
1. **새로운 메소드 추가**:
- 관리자가 특정 트랙의 공지만 조회할 수 있는 `getNoticesForTrack(Long trackId)` 메소드.
- 사용자가 속한 트랙의 공지만 조회할 수 있는 `getNoticesForUserByTrack(Long userId, Long trackId)` 메소드.
2. **기능 개선**:
- 관리자와 일반 사용자의 권한을 확인하여 적절한 공지만 조회하도록 보안 강화.
- 트랙 ID가 유효하지 않거나 권한이 없는 경우에 대한 예외 처리 로직 강화.
3. **코드 최적화**:
- 중복 코드 제거 및 공통 로직을 메서드로 분리하여 코드의 가독성 및 유지보수성 향상.
- Postman을 통해 새로운 메소드의 로직을 검증.
- Postman을 통해 API가 전체 시스템과 올바르게 통합되는지 확인.
> feat: 트랙 공지 전체 조회

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackNoticeController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackNoticeUpdateRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackNotice.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackNoticeService.java
이 Pull Request에서는 관리자가 트랙 공지를 수정할 수 있는 기능을 구현합니다. 이 기능은 시스템의 유연성을 향상시키고, 관리자가 공지사항을 시의적절하게 업데이트할 수 있게 합니다.
1. **트랙 공지 수정 API**:
- 관리자 권한을 가진 사용자만 트랙 공지를 수정할 수 있습니다.
- 공지 제목과 내용을 업데이트하는 `PUT` 엔드포인트(`/tracks/notices/{noticeId}`)를 추가했습니다.
2. **서비스 로직 개선**:
- `TrackNoticeService`에 `updateTrackNotice` 메서드를 추가하여, 공지 내용의 검증과 업데이트 로직을 구현했습니다.
3. **DTO 추가**:
- 공지 수정을 위한 `TrackNoticeUpdateRequestDTO`를 새로 생성하여, API 요청에서 사용자 입력을 안전하게 처리합니다.
4. **권한 검증**:
- 공지 수정 작업에 대한 접근 권한을 검증하는 로직을 강화했습니다.
- **효율성 향상**: 관리자가 공지사항을 더 빠르고 쉽게 업데이트할 수 있습니다.
- **보안 강화**: 적절한 권한 검증을 통해 시스템의 안전성을 유지합니다.
- Postman을 사용하여 API의 동작을 매뉴얼 테스트했습니다.
- 수정된 공지 내용이 정상적으로 반영되었고, 적절한 권한 없이 접근할 경우 에러 메시지가 반환되는 것을 확인했습니다.
> feat: 트랙 공지 수정

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackNoticeController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackNoticeService.java
- 트랙 공지 단일 조회 기능을 구현하여, 관리자와 사용자가 트랙 공지를 조회할 수 있도록 함. 사용자는 자신이 속한 트랙의 공지만 조회 가능.
1. **Service 계층 수정**: `TrackNoticeService`에 `getTrackNotice` 메소드를 추가하여, 사용자와 관리자의 권한을 검증 후 트랙 공지를 제공.
2. **Repository 계층 수정**: `TrackNoticeRepository`에 트랙 ID를 기준으로 공지를 조회하는 JPA 쿼리 메소드를 추가.
3. **Controller 계층 수정**: `TrackNoticeController`에 경로 변수를 사용하여 공지 ID에 따른 조회 엔드포인트를 설정.
4. **Exception Handling**: 적절한 예외 처리를 추가하여, 권한이 없거나 요청된 공지가 없는 경우 사용자에게 알려줄 수 있도록 함.
- 관리자와 일반 사용자 계정을 통해 각각의 시나리오에 대한 접근성을 테스트. 관리자는 모든 트랙의 공지를 조회할 수 있고, 사용자는 자신이 속한 트랙의 공지만 조회할 수 있음을 확인.
- API 테스트를 포스트맨으로 수행하여, 모든 가능한 경우에 대한 응답과 예외가 적절히 처리되는지 검증.
- 이 기능을 통해 플랫폼 사용자가 더욱 유연하게 정보를 접근할 수 있으며, 관리자는 효율적인 트랙 관리가 가능해짐.
- 사용자 경험 개선 및 시스템의 안정성 향상.
> feat: 트랙 공지 단일 조회

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackParticipantsController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackUpdateRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackParticipantsService.java
이 PR은 `TrackParticipantsService` 및 `TrackParticipantsController` 클래스의 `updateParticipantTrack` 메소드를 리팩터링하여 새로운 트랙의 이름 대신 ID를 받도록 변경했습니다. 이 변경으로 여러 가지 이점을 제공합니다:
1. **안정성**: 트랙 ID는 고유하며 변경되지 않아 트랙 이름보다 더 안정적인 식별자입니다. 트랙 이름은 변경될 수 있습니다.
2. **성능**: ID를 사용하면 데이터베이스 쿼리가 더 빠르고 효율적일 수 있습니다.
주요 변경 사항은 다음과 같습니다:
- `TrackUpdateRequestDTO` 클래스에 `newTrackId` 필드를 추가했습니다.
- `TrackParticipantsController` 클래스의 `updateParticipantTrack` 메소드를 리팩터링하여 `TrackUpdateRequestDTO` 객체를 받도록 수정했습니다.
- `TrackParticipantsService` 클래스의 `updateParticipantTrack` 메소드를 리팩터링하여 새 트랙의 ID를 사용하여 트랙 엔티티를 찾도록 했습니다.
- 더 이상 필요하지 않은 `TrackRepository` 인터페이스에서 `findByTrackName` 메소드를 제거했습니다.
> fix: 트랙 참여자의 트랙 수정기능의 수정

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackWeekController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackWeekCreationRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackWeekCreationResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackWeek.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/repository/TrackWeekRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackWeekService.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
이 PR은 트랙 주차 생성 기능을 개선하고, 필요한 날짜 유효성 검사를 추가하는 것을 목표로 합니다. 기존 시스템에서 트랙 주차를 생성할 때 일부 유효성 검사가 누락되어, 논리적으로 부적합한 날짜 입력을 방지하는 로직을 강화하였습니다.
1. **트랙 주차 생성 로직**: `TrackWeekController`에 `/tracks/{trackId}/weeks` 엔드포인트를 통해 트랙 주차를 생성하는 기능을 구현합니다.
2. **날짜 유효성 검사 추가**:
- 시작일은 현재 날짜 이후여야 하며, 종료일은 시작일 이후가 되어야 합니다.
- 유효성 검사는 `TrackWeekService` 레벨에서 수행되며, DTO에서는 날짜 형식만을 검증합니다.
- 위 조건을 만족하지 않을 때는 `ErrorCode`에 정의된 `START_DATE_BEFORE_CURRENT`와 `INVALID_DATE_RANGE`를 사용하여 예외를 발생시킵니다.
3. **예외 처리 강화**: 서비스 레벨과 컨트롤러 레벨에서의 예외 처리를 강화하여 API 사용자에게 명확한 에러 메시지를 제공합니다.
이 변경은 사용자가 시스템을 보다 효과적으로 사용할 수 있도록 지원하고, 데이터 무결성을 보장하기 위해 필요합니다. 이를 통해 트랙 관리가 더욱 효율적이고 오류 없이 수행될 수 있습니다.
- 포스트맨(Postman)을 사용하여 API 엔드포인트에 대한 통합 테스트를 수행하였습니다.
- 불가능한 날짜 입력 시 API가 적절한 에러 코드와 메시지를 반환하는지 확인하였습니다.
> feat: 트랙 주차 생성

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackWeekController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackWeekUpdateRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackWeekUpdateResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/entity/TrackWeek.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackWeekService.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
- 이 PR은 관리자가 트랙 주차의 이름, 시작일, 종료일을 선택적으로 수정할 수 있는 기능을 구현합니다.
- `TrackWeekService`에 `updateTrackWeek` 메서드를 수정하여 선택적으로 필드를 업데이트할 수 있도록 했습니다.
- 시작일이 현재 날짜보다 이전이거나, 종료일이 시작일보다 이전일 경우 예외를 처리하는 로직을 추가했습니다.
- `TrackWeekUpdateRequestDTO`를 사용하여 요청 데이터를 수신하고, 유효성 검사를 수행합니다.
- `TrackWeekUpdateResponseDTO`를 통해 수정된 트랙 주차 정보를 응답합니다.
- 관리자는 필요에 따라 트랙 주차 정보의 일부만 수정할 수 있으며, 데이터 무결성을 유지할 수 있습니다.
- 사용자 경험이 개선되고, 데이터 처리의 유연성이 향상됩니다.
- 시작일은 현재 날짜 이후로만 설정 가능합니다.
- 종료일은 시작일 이후로만 설정 가능합니다.
- 관리자 권한이 필요한 API입니다.
> feat: 트랙 주차 수정

- src/main/java/wercsmik/spaghetticodingclub/domain/track/controller/TrackWeekController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/dto/TrackWeekListResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackWeekService.java
이 PR은 트랙 주차 전체 조회 기능을 추가하고, `TrackWeekService` 내의 DTO 변환 메소드의 이름을 명확화하여, 생성, 수정, 조회 기능에서 반환되는 DTO 타입을 더 명확하게 구분하고자 합니다. 이러한 개선은 서비스의 기능 확장과 동시에 코드의 가독성 및 유지보수성을 크게 향상시킬 것입니다.
- **전체 조회 기능 추가**: `TrackWeekService`에 `findAllTrackWeeksByTrackId` 메소드를 추가하여 지정된 트랙 ID에 대한 모든 주차 정보를 조회할 수 있는 기능을 구현하였습니다.
- **DTO 변환 메소드 이름 변경**: `convertToDTO` 메소드를 기능에 따라 `convertToCreationDTO`와 `convertToListDTO`로 분리하여 반환되는 DTO의 용도를 명확하게 구분하였습니다.
- **Controller 업데이트**: `TrackWeekController`에 전체 조회를 위한 GET 엔드포인트를 추가하여 외부에서 접근 가능하게 구성하였습니다.
- **기능성 향상**: 사용자 및 관리자는 특정 트랙에 대한 모든 주차 정보를 쉽게 조회할 수 있습니다.
- **코드 가독성 향상**: 메소드명을 통해 반환되는 객체의 종류를 즉시 이해할 수 있습니다, 또한 각각의 용도에 맞는 DTO 변환을 명확히 함으로써 잠재적인 오류의 범위를 줄일 수 있습니다.
- **유지보수성 강화**: 메소드의 명확한 명명규칙은 향후 코드 수정 시 오류 가능성을 줄이고, 개발자가 기능과 관련된 부분을 빠르게 이해하고 접근할 수 있게 도와줍니다.
> feat: 트랙 전체 주차 조회

- src/main/java/wercsmik/spaghetticodingclub/domain/team/controller/TeamController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/dto/TeamCreationRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/dto/TeamCreationResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/dto/TeamRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/dto/TeamResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/entity/Team.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/entity/TeamMember.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/repository/TeamMemberRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/repository/TeamRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/service/TeamService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
**개요**
- 이 PR은 사용자가 팀을 생성할 수 있게 하는 기능을 추가합니다. 
- 이 기능은 특정 트랙 주차에 팀을 할당하여 사용자들이 그룹으로 활동할 수 있게 합니다.
**상세 내용**
- `Team` 엔티티에 `members` 필드를 추가하여 다대다 관계를 구현하였습니다.
- `TeamService`에서는 팀 생성 로직을 처리합니다. 사용자 목록을 받아 팀을 구성하고, 해당 팀을 데이터베이스에 저장합니다.
**테스트**
- Postman을 통해 API를 호출하여 실제 동작을 검증하였습니다.
> feat: 팀 생성

- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/controller/SchedulerController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/dto/SchedulerResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/repository/SchedulerRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/service/SchedulerService.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
이 PR은 팀(원)의 일정 전체 조회 기능을 추가하고, 팀내에 속한 모든 유저들의 모든 일정을 조회 하고자 하는것을 목표로 합니다. 
- **팀(원)의 일정 전체 조회 로직 구현**: `SchedulerService`에 팀에 속한 멤버들을 조회하여 멤버들을 List 형태로 만든후 각 멤버들의 일정을 다시 List하여 가져오는 방식으로 정보를 조회할 수 있는 기능을 구현하였습니다.
- **예외 처리**: 정보 조회 할 시 팀의 유무, 팀원의 유무에 대하여 예외처리를 추가 하였습니다.
- **기능성 향상**: 사용자 및 관리자는 특정 팀에 대한 모든 일정 정보를 쉽게 조회할 수 있습니다.
- 포스트맨(Postman)을 사용하여 API 엔드포인트에 대한 통합 테스트를 수행하였습니다.
- 불가능한 날짜 입력 시 API가 적절한 에러 코드와 메시지를 반환하는지 확인하였습니다.
> feature/shcedule 팀(원)의 일정 전체 조회

- src/main/java/wercsmik/spaghetticodingclub/domain/team/controller/TeamController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/dto/MultipleTeamCreationRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/team/service/TeamService.java
- 여러 팀을 동시에 생성할 수 있어야 합니다.
- 각 팀에는 여러 명의 멤버를 포함할 수 있어야 합니다.
- 관리자 권한을 가진 사용자만이 팀을 생성할 수 있어야 합니다.
- 관리자가 여러 팀을 한 번의 요청으로 생성할 수 있어 작업 효율성이 향상됩니다.
- 팀 생성 시 각 팀에 포함된 멤버들의 정보도 함께 반환되어 프론트엔드에서의 추가적인 데이터를 요청할 필요가 없습니다.
> feat: 팀 생성 시 여러개의 팀 동시에 생성

- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/controller/UnlikeController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/dto/UnlikeCreationRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/dto/UnlikeCreationResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/dto/UnlikeRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/dto/UnlikeResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/entity/Unlike.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/repository/UnlikeRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/unlike/service/UnlikeService.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
팀 내에서 비호감도 기록을 생성할 수 있는 기능을 도입합니다.
각 팀원은 팀 내 다른 팀원에게 한 번만 비호감도를 줄 수 있어, 각 멤버의 피드백이 중복 없이 등록될 수 있습니다.
**기술적 변경 사항:**
1. **엔티티 변경 사항:**
- 발신자, 수신자, 팀, 원인, 타임스탬프를 필드로 가지는 `Unlike` 엔티티 추가.
2. **리포지토리 변경 사항:**
- `senderUserId`와 `teamId`로 비호감도 존재 여부를 확인하는 메소드를 `UnlikeRepository`에 추가.
3. **서비스 레이어:**
- 새로운 비호감도를 생성하는 로직을 처리하는 `UnlikeService` 내에 `createUnlike` 메소드 추가.
- 발신자와 수신자가 팀의 일원임을 확인하고 동일 팀 내에서 발신자가 이미 비호감도를 주지 않았는지 검증하는 유효성 검사 포함.
4. **컨트롤러 레이어:**
- 비호감도 생성과 관련된 HTTP 요청을 관리하는 `UnlikeController` 생성.
**테스트 방법:**
1. 비호감도 생성 엔드포인트 `/unlike`로 이동합니다.
2. `senderUserId`, `receiverUserId`, `teamId`, `cause`를 포함하는 JSON 본문을 제공합니다.
3. 요청이 성공 응답을 반환하고 데이터베이스에 비호감도 기록이 생성되는지 확인합니다.
4. 동일 팀에 대해 중복 비호감도를 생성하여 유효성 검증이 제대로 작동하는지 확인합니다.
**문서화:**
- 새 비호감도 생성 엔드포인트의 세부사항과 예제를 포함하여 API 문서를 업데이트했습니다.
> feat: 비호감도 생성

- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/controller/SchedulerController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/dto/SchedulerUpdateRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/entity/Scheduler.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/repository/SchedulerRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/service/SchedulerService.java
이 PR은 일정 수정 기능을 추가하고, 일정을 작성한 본인만 일정을 수정할 수 있으며 일정을 수정할 경우 다양한 경우( 제목만입력, 제목과 시작시간입력, 제목과 종료시간 입력, 제목과 시작 종료시간 입력)에도 변경이 가능하도록 하여야 하며 수정하고자 하는 일정의 시간이 다른 일정과 시간이 겹쳐서는 안되도록 하여야 합니다.
- **사용자가 해당 일정을 소유하고 있는지 확인 추가**
- **StartTime 또는 EndTime이 업데이트되는지 여부 확인** : 만약 내용이 없을 경우 DB를 반영하여 저장된 기존 시간으로 
- 응답 예시 1
```json
{
"title": "3개다 수정하기",
"startDate": "2024-06-10T00:00:00",
"endDate": "2024-06-14T23:59:59"
}
```
- 결과값:
```json
{
"message": "일정 수정 성공",
"payload": {
"schedulerId": 8,
"userId": 2,
"title": "3개다 수정하기",
"startTime": "2024-06-12T00:00:00",
"endTime": "2024-06-17T06:30:00"
}
}
```
- 응답 예시 2
```json
{
"title": "제목만 수정",
}
```
- 결과값:
```json
{
"message": "일정 수정 성공",
"payload": {
"schedulerId": 8,
"userId": 2,
"title": "제목만 수정",
"startTime": "2024-06-12T00:00:00",
"endTime": …
```
> feature/shcedule 일정 수정 

- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/controller/SchedulerController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/schedule/service/SchedulerService.java
이 PR은 일정을 삭제할 수 있는 기능을 도입합니다.
오로지 본인이 생성 했던 일정만 삭제 가능하며 본인 외에 다른 사용자가 생성했던 일정은 삭제 할 수 없습니다.
**기술적 변경 사항:**
1. **SchceduleController:**
- 일정 삭제와 관련된 HTTP 요청을 관리하는 API 추가.
2. **SchceduleService:**
- 일정 삭제를 위해 삭제하려는 일정 존재여부, 본인이 작성했던 일정인지에 대한 여부 확인 로직 추가
- 포스트맨(Postman)을 사용하여 API 테스트를 수행하였습니다.
- 존재하지않는 일정일 경우, 삭제하려는 일정이 본인이 아닌경우 에 대한 예외처리를 확인하였습니다.-
> feature/shcedule: 일정 삭제 

- src/main/java/wercsmik/spaghetticodingclub/domain/auth/controller/AuthController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/DeleteRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/track/service/TrackParticipantsService.java
- src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtUtil.java
이 PR은 유저 탈퇴 기능을 추가하며 탈퇴를 할 경우 오로지 사용자 본인만 탈퇴가 가능하며, 또한 탈퇴시 비밀번호를 입력함으로서 본인이 정말로 탈퇴하는것이 맞는지에대해서 다시한번 확인 과정을 거치는 구조로 구현 되었습니다.
- **DeleteRequestDTO 추가**: 탈퇴 시 비밀번호를 입력함으로서 본인 확인과 혹시나 모를 실수로 인해 탈퇴할 가능성을 없애도록 합니다.
- **실수로 인한 탈퇴 경우 방지**: 탈퇴시 비밀번호 입력으로 실수로 인해 탈퇴할 경우를 방지하면서 본인만 탈퇴가 가능합니다.
> feature/auth: 유저 탈퇴 기능 구현

- src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/LoginResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthenticationFilter.java
해당 PR은 유저 로그인시 Long trackId 값을 가져오기 위하여 수정한 내용입니다.
> fix: 유저 로그인 성공 응답에 trackId 값 추가

- src/main/java/wercsmik/spaghetticodingclub/domain/user/controller/UserController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/dto/ProfileResponseDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/service/UserService.java
이 PR은 로그인한 사용자가 본인 프로필 조회 기능을 추가하였으며, 응답값에서 trackId 와 현재시간을 기준으로 속해있는 trackWeekId가 나오도록 반영하였으며 특정 유저 프로필 조회 기능과 중복된코드를 공통로직으로 정리함으로서 코드의 가독성과 유지보수성을 높이는데 목적이 있습니다.
- **본인 프로필 조회 로직 구현**: 로그인한 사용자가 본인의 정보만 가져올 수 있도록 API를 추가 하였습니다.
- **ProfileResponseDTO 변경**: 기존 응답값에서 유저가 속해있는 trackId와 현재 시간을 기준으로 속해있는 trackWeekId를 가져오도록 반영하였습니다..
- **공통로직 정리**: 특정 유저 프로필 조회 기능과 중복코드 부분이 많이 겹침으로 중복되는 부분은 createProfileResponseDTO 메소드 로 공통로직으로 정리하였습니다.
- **코드의 가독성과 유지보수성 향상**
- **사용자 본인의 모든정보를 한번가져올 수 있게됨**
- 포스트맨(Postman)을 사용하여 API 엔드포인트에 대한 통합 테스트를 수행하였습니다.
> feature: 본인 프로필 조회 API구현 / 공통로직 정리

- src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
삭제하려는 유저가 TeamMember에 속해있을 경우 외래키 값으로 인해서 삭제 처리가 되지않음
이에 대해서 User 엔티티에서 TeamMember와의 양방향 관계를 설정하고 cascade = CascadeType.ALL 및 orphanRemoval = true를 추가함으로서 같이 삭제 될수 있도록 처리함.
> bugfix: 유저 삭제시 생기던 403 오류 수정

- src/main/java/wercsmik/spaghetticodingclub/domain/user/controller/UserController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/dto/UpdateUserNameRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/service/UserService.java
- 사용자(Admin, User)는 본인의 이름을 변경 할 수 있어야 합니다.
- Admin 사용자는 User 사용자의 이름을 변경 할 수 있어야 합니다.
- User 사용자는 본인 외에 다른 사용자들의 이름을 변경 할 수 없어야 합니다.
- 사용자들은 본인의 이름을 변경 할 수 있습니다.
- 회원가입 한 User 사용자들의 이름이 동일한경우 Admin 사용자는 User 사용자들을 구분하기 위하여 임의적으로 이름을 수정하여 구분 할 수 있습니다.
- 포스트맨(Postman)을 사용하여 API 엔드포인트에 대한 통합 테스트를 수행하였습니다.
> feature/user 사용자 이름 변경 기능 구현

- build.gradle
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/controller/AuthController.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/dto/EmailCheckRequestDTO.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/entity/EmailVerification.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/repository/EmailVerificationRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/repotiroy/EmailVerificationRepository.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/AuthService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/EmailService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/auth/service/EmailVerificationCleanupService.java
- src/main/java/wercsmik/spaghetticodingclub/domain/user/entity/User.java
- src/main/java/wercsmik/spaghetticodingclub/global/config/EmailConfig.java
- src/main/java/wercsmik/spaghetticodingclub/global/config/WebSecurityConfig.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/ErrorCode.java
- src/main/java/wercsmik/spaghetticodingclub/global/exception/GlobalExceptionHandler.java
- src/main/java/wercsmik/spaghetticodingclub/global/jwt/JwtAuthenticationFilter.java
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
이 PR은 '본인 이메일 인증을위한 인증링크발송, 추천인 이메일 인증을 위한 인증링크 발송, 이메일 인증 확인' 총 3개의 기능을 구현한 내용이며 회원가입시 수강생은 본인인증을 통한 가입, 관리자는 본인인증과 추천인인증을 통하여 무분별한 회원가입을 막기위한 내용입니다.
수강생의 경우 본인 이메일 인증이 확인된다면 회원가입이 가능하지만 관리자의 경우 본인 이메일을 인증이 확인된 상태여야만 '추천인 이메일 인증링크 발송'기능을 통해서 추천인 관리자의 이메일로 인증링크를 보내 인증후 새로운 관리자로 가입이 가능합니다.
발송 이메일은 토큰 값으로 DB에 저장되며 회원가입이 완료될경우 관련된 토큰값이 삭제되거나, 재발송 요청시 이전 토큰값을 삭제후 발송처리하며, 유효시간이 지난 토큰값은 스케줄러에 의하여 일정시간마다 DB를 정리함으로서 DB성능의 저하를 막을 수 있습니다. 
수강생의 경우 본인 인증, 관리자의 경우 본인 인증, 추천인 인증을 통하여 무분별한 사용자의 회원가입을 막을 수 있습니다.
> feature/Auth 본인 이메일 인증링크 발송 기능, 추천인 이메일 인증링크 발송 기능, 이메일 검증 3개 기능 구현
